//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krous_Ex
{


    public partial class Testing3
    {

        /// <summary>
<<<<<<< Updated upstream:Krous_Ex/Testing3.aspx.designer.cs
        /// gvCustomers control.
=======
        /// txtDate control.
>>>>>>> Stashed changes:Krous_Ex/Testing.aspx.designer.cs
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< Updated upstream:Krous_Ex/Testing3.aspx.designer.cs
        protected global::System.Web.UI.WebControls.GridView gvCustomers;
=======
        protected global::System.Web.UI.WebControls.TextBox txtDate;
>>>>>>> Stashed changes:Krous_Ex/Testing.aspx.designer.cs
    }
}
